
---
- name: Add user to host
  hosts: all
  become: yes
  vars:
    usuario: "user"
  tasks:
    - name: Create user on Ubuntu/Debian
      user:
        name: "{{ usuario }}"
        groups: sudo
        shell: /bin/bash
        append: yes
      when:
        - ansible_facts['distribution'] == "Ubuntu" or ansible_facts['distribution'] == "Debian"
    - name: Create user on CentOS
      user:
        name: "{{ usuario }}"
        groups: wheel
        shell: /bin/bash
        append: yes
      when:
        - ansible_facts['distribution'] == "CentOS"
    - name: Add ssh key
      authorized_key:
        user: "{{ usuario }}"
        state: present
        key: "{{ lookup('file', '../keys/{{ usuario }}.pub') }}"
    - name: Create sudoers
      file:
        path: "/etc/sudoers.d/{{ usuario }}"
        state: touch
    - name: Add line to sudoers
      lineinfile:
        path: "/etc/sudoers.d/{{ usuario }}"
        line: "{{ usuario }} ALL=(ALL) NOPASSWD:ALL"
    - name: Add user to SSH config
      replace:
        backup: yes
        dest: /etc/ssh/sshd_config
        regexp: '^(AllowUsers(?!.*\b{{ usuario }}\b).*)$'
        replace: '\1 {{ usuario }}'
      when:
        - ansible_facts['distribution'] == "CentOS"
        - ansible_facts['distribution_major_version'] == "6"
      notify:
        - Restart SSHD
  handlers:
    - name: Restart SSHD
      service:
        name: sshd
        state: restarted
