---
- name: Instalar Zabbix Agent 2 con repositorio específico según sistema operativo
  hosts: all
  become: yes

  vars:
    zabbix_repo_base_url: "https://repo.zabbix.com/zabbix/6.0"

  tasks:
    - name: Definir URL del repositorio según sistema operativo y versión
      set_fact:
        zabbix_repo_url: >-
          {% if ansible_facts['os_family'] == "Debian" and ansible_facts['distribution'] == "Ubuntu" %}
            {{ zabbix_repo_base_url }}/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest+ubuntu{{ ansible_facts['distribution_version'] | regex_replace('\\..*', '') }}.04_all.deb
          {% elif ansible_facts['os_family'] == "Debian" and ansible_facts['distribution'] == "Debian" %}
            {{ zabbix_repo_base_url }}/debian/pool/main/z/zabbix-release/zabbix-release_latest+debian{{ ansible_facts['distribution_major_version'] }}_all.deb
          {% else %}
            ""
          {% endif %}

    - name: Verificar que la URL del repositorio es válida
      ansible.builtin.assert:
        that:
          - zabbix_repo_url != ""
        msg: "No se encontró una URL de repositorio compatible para el sistema operativo actual."

    - name: Descargar el repositorio de Zabbix
      ansible.builtin.get_url:
        url: "{{ zabbix_repo_url }}"
        dest: /tmp/zabbix-release.deb

    - name: Instalar el paquete del repositorio Zabbix
      ansible.builtin.command:
        cmd: "dpkg -i /tmp/zabbix-release.deb"
      register: dpkg_output
      ignore_errors: true

    - name: Corregir dependencias faltantes
      ansible.builtin.apt:
        update_cache: yes
        name: "{{ dpkg_output }}"
        state: present

    - name: Instalar Zabbix Agent 2
      ansible.builtin.apt:
        name: zabbix-agent2
        state: present

    - name: Configurar zabbix_agent2.conf con la IP del servidor Zabbix
      ansible.builtin.lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: '^Server='
        line: "Server={{ zabbix_server_ip }}"
        state: present
      notify:
        - restart zabbix-agent2

    - name: Habilitar y asegurar que el servicio Zabbix Agent 2 esté activo
      ansible.builtin.service:
        name: zabbix-agent2
        enabled: yes
        state: started

  handlers:
    - name: restart zabbix-agent2
      ansible.builtin.service:
        name: zabbix-agent2
        state: restarted
