---
- name: Instalar Zabbix Agent 2 según el sistema operativo
  hosts: all
  become: yes

  vars:
    zabbix_server_ip: "zabbix.vozitel.com"
    repo_urls:
      CentOS6: "https://repo.zabbix.com/zabbix/7.0/rhel/6/x86_64/zabbix-release-latest.el6.noarch.rpm"
      CentOS7: "https://repo.zabbix.com/zabbix/7.0/rhel/7/x86_64/zabbix-release-latest.el7.noarch.rpm"
      Debian10: "https://repo.zabbix.com/zabbix/7.0/debian/pool/main/z/zabbix-release/zabbix-release_latest+debian10_all.deb"
      Debian11: "https://repo.zabbix.com/zabbix/7.0/debian/pool/main/z/zabbix-release/zabbix-release_latest+debian11_all.deb"
      Debian12: "https://repo.zabbix.com/zabbix/7.0/debian/pool/main/z/zabbix-release/zabbix-release_latest+debian12_all.deb"
      Ubuntu20: "https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest+ubuntu20.04_all.deb"
      Ubuntu22: "https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest+ubuntu22.04_all.deb"
      Ubuntu24: "https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest+ubuntu24.04_all.deb"

  tasks:
    - name: Instalar Zabbix según el sistema operativo
      block:
        - name: Instalar el repositorio de Zabbix
          ansible.builtin.yum:
            name: "{{ repo_urls[ansible_facts['distribution'] ~ ansible_facts['distribution_version'] | regex_search('^6|^7') | first | lower] }}"
            state: present
          when: ansible_facts['os_family'] == "RedHat"

        - name: Descargar el repositorio de Zabbix
          ansible.builtin.get_url:
            url: "{{ repo_urls[ansible_facts['distribution'] ~ ansible_facts['distribution_version'] | regex_search('^10|^11|^12|^20|^22|^24') | first | lower] }}"
            dest: /tmp/zabbix-release.deb
          when: ansible_facts['os_family'] == "Debian"

        - name: Instalar el repositorio de Zabbix (Debian)
          ansible.builtin.command:
            cmd: dpkg -i /tmp/zabbix-release.deb
          when: ansible_facts['os_family'] == "Debian"

        - name: Limpiar la caché de yum (CentOS)
          ansible.builtin.command:
            cmd: yum clean all
          when: ansible_facts['os_family'] == "RedHat"

        - name: Actualizar el índice de paquetes (Debian)
          ansible.builtin.apt:
            update_cache: yes
          when: ansible_facts['os_family'] == "Debian"

        - name: Instalar Zabbix Agent 2 y plugins
          ansible.builtin.apt:
            name: zabbix-agent2,zabbix-agent2-plugin-*
            state: present
          when: ansible_facts['os_family'] == "Debian"

        - name: Instalar Zabbix Agent 2 y plugins
          ansible.builtin.yum:
            name: zabbix-agent2,zabbix-agent2-plugin-*
            state: present
          when: ansible_facts['os_family'] == "RedHat"

        - name: Configurar la dirección del servidor Zabbix
          ansible.builtin.lineinfile:
            path: /etc/zabbix/zabbix_agent2.conf
            regexp: '^Server='
            line: "Server={{ zabbix_server_ip }}"
            state: present

        - name: Reiniciar y habilitar el servicio Zabbix Agent 2
          ansible.builtin.systemd:
            name: zabbix-agent2
            state: restarted
            enabled: yes
