---
- name: Instalar Zabbix Agent 2
  hosts: all            # Define el grupo de hosts en el archivo de inventario
  become: yes           # Usa sudo para comandos que lo requieran

  vars:
    zabbix_repo_url_debian: "https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-2%2Bubuntu20.04_all.deb"
    zabbix_repo_url_centos: "https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-6.0-2.el8.noarch.rpm"
    zabbix_server_ip: "zabbix.vozitel.com"  # IP de nuestro servidor Zabbix

  tasks:
    - name: Instalar el repositorio de Zabbix (Debian/Ubuntu)
      ansible.builtin.apt:
        deb: "{{ zabbix_repo_url_debian }}"
        state: present
      when: ansible_os_family == "Debian"

    - name: Instalar el repositorio de Zabbix (CentOS/RHEL)
      ansible.builtin.yum:
        name: "{{ zabbix_repo_url_centos }}"
        state: present
      when: ansible_os_family == "RedHat"

    - name: Actualizar el cache de apt (solo Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Instalar Zabbix Agent 2
      ansible.builtin.package:
        name: zabbix-agent2
        state: present

    - name: Configurar zabbix_agent2.conf con la IP del servidor Zabbix
      ansible.builtin.lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: '^Server='
        line: "Server={{ zabbix_server_ip }}"
        state: present
      notify:
        - restart zabbix-agent2

    - name: Habilitar y asegurar que el servicio Zabbix Agent 2 esté activo
      ansible.builtin.service:
        name: zabbix-agent2
        enabled: yes
        state: started

  handlers:
    - name: restart zabbix-agent2
      ansible.builtin.service:
        name: zabbix-agent2
        state: restarted
